version: '3.4'

services:
  api.serilog.file:
    image: ${DOCKER_REGISTRY-}apiserilogfile
    build:
      context: .
      dockerfile: Api.Serilog.File/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44338
    ports:
      - "50502:50502"
      - "44338:44338"
    volumes:
      - "C:\\Logs:/app"
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro